### ISSUE TITLE
RubyMine 4.5 EAP: Found interface git4idea.repo.GitRepository, but class was expected

### ISSUE THREAD

**Issue by parameme** [jexp/jetbrains-heroku-plugin#18]
Hi Michael, 

RubyMine told me to send you (as registered plugin vendor) the following IDE error stacktrace.

Context/use-case was starting the RubyMine 4.5 EAP (Nire) environment, loading an existent git controlled project. Reproducible.

Seems similar to #15 with a change in the underlying git API provided by Idea.

Hope the information helps,

Kind Regards,

(parameme)

```
Found interface git4idea.repo.GitRepository, but class was expected: Found interface git4idea.repo.GitRepository, but class was expected
java.lang.IncompatibleClassChangeError: Found interface git4idea.repo.GitRepository, but class was expected
    at com.jetbrains.heroku.git.GitRemoteHandler11.getRemotes(GitRemoteHandler11.java:47)
    at com.jetbrains.heroku.git.GitRemoteHandler11.findRemote(GitRemoteHandler11.java:26)
    at com.jetbrains.heroku.git.GitHelper.findHerokuOrigin(GitHelper.java:93)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.doUpdate(HerokuSetupWindow.java:66)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.createContentPane(HerokuSetupWindow.java:54)
    at com.jetbrains.heroku.ui.HerokuToolWindow.<init>(HerokuToolWindow.java:40)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.<init>(HerokuSetupWindow.java:224)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindow(HerokuToolWindowFactory.java:43)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindowContent(HerokuToolWindowFactory.java:34)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:448)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11.run(ToolWindowManagerImpl.java:498)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
    at java.awt.EventQueue.access$000(EventQueue.java:85)
    at java.awt.EventQueue$1.run(EventQueue.java:643)
    at java.awt.EventQueue$1.run(EventQueue.java:641)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:652)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:719)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:544)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by thejoecarroll** [comment]
Same problem here: it doesn't work on my Mac running RubyMine 4.5.4 under JDK 1.6.0_35 on OS X 10.8 but caused the following fatal error when it tried to initialise (after correctly configuring the API key):

Found interface git4idea.repo.GitRepository, but class was expected: Found interface git4idea.repo.GitRepository, but class was expected
java.lang.IncompatibleClassChangeError: Found interface git4idea.repo.GitRepository, but class was expected
    at com.jetbrains.heroku.git.GitRemoteHandler11.getRemotes(GitRemoteHandler11.java:47)
    at com.jetbrains.heroku.git.GitRemoteHandler11.findRemote(GitRemoteHandler11.java:26)
    at com.jetbrains.heroku.git.GitHelper.findHerokuOrigin(GitHelper.java:93)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.doUpdate(HerokuSetupWindow.java:66)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.createContentPane(HerokuSetupWindow.java:54)
    at com.jetbrains.heroku.ui.HerokuToolWindow.<init>(HerokuToolWindow.java:40)
    at com.jetbrains.heroku.ui.HerokuSetupWindow.<init>(HerokuSetupWindow.java:224)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindow(HerokuToolWindowFactory.java:43)
    at com.jetbrains.heroku.ui.HerokuToolWindowFactory.createToolWindowContent(HerokuToolWindowFactory.java:34)
    at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentInitialized(ToolWindowImpl.java:448)
    at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$11.run(ToolWindowManagerImpl.java:498)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:333)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:702)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:663)
    at java.awt.EventQueue$2.run(EventQueue.java:661)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:672)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:719)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:544)
    at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:421)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:379)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by thejoecarroll** [comment]
Appears to fail if there's an existing git repo in the project. However, if I create a new project the Heroku plugin window loads and works, but says in red "Git-Integration: disabled (please enable)" without any more information about what exactly this means in this context.

**Comment by MatthiasWinzeler** [comment]
Experiencing the same problem using RubyMine 4.5.4 on Ubuntu 12.04 (OpenJDK 64-bit 1.6_u24)

**Comment by nerakhon** [comment]
Same thing seems to happen in Webstorm on OS X 10.8.2. Without VCS it fails and complains Git is not configured with Git it fails on the exception.

**Comment by kevinmccaughey** [comment]
Same here on Windows. It happened right after I made some changes to do with git repos. Even though I put things back the way they were, it now seems perma broken.

I use bitbucket too, in case that might be an issue.

**Comment by jexp** [comment]
Hi All,

Sorry, that it took so long. I fixed the git4idea class change issue which was another API incompatibility between JetBrains product versions. Also fixed issues with changed icon paths.

Cheers Michael

**Comment by nerakhon** [comment]
Great, any idea when this updated version makes it to JetBrains repo?

**Comment by jexp** [comment]
Should already be there, is version 0.4.0

**Comment by nerakhon** [comment]
At least for me it does not look like, webstorm still shows 3.9 in the plugin manager UI.

**Comment by nerakhon** [comment]
May be a clue, github lacks any pushes from you today/yesterday, that sounds kind off strange ... may be some mistake happened?

**Comment by jexp** [comment]
Right, sorry, just uploaded it to the plugin repo, worked on it from 2 AM to 5 AM :)

**Comment by nerakhon** [comment]
Great, thx a million! I will let you know on twitter how my testing went!

**Comment by kevinmccaughey** [comment]
Thanks a lot Michael - your work is greatly appreciated :)
